# 编排php,redis,nginx容器
version: "3.6" # 确定docker-composer文件的版本
services: # 代表就是一组服务 - 简单来说一组容器

  swoft:
    image: php73_php-fpm
    build:
      context: ./ #路径
    container_name: php73_swoft
    ports:
      - "9000:9000"
      - "9501:9501"
      - "9502:9502"
      - "9503:9503"
      - "9504:9504"
      - "18306:18306"
    volumes:
      - ./swoft:/var/www/html/swoft
      - ./conf/php.ini:/usr/local/etc/php/php.ini
    stdin_open: true
    tty: true
    working_dir: /var/www/html/swoft/bin/
    privileged: true
    networks:
      app_swoft:
        ipv4_address: 192.160.1.112

networks:
  app_swoft:
    external:
      name: redis5sm