version: "3.6"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
       - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    stdin_open: true
    tty: true
    privileged: true
    networks:
       cache-network:
          ipv4_address: 192.160.1.20
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
networks:
 cache-network:
    external:
       name: redis5sm