version: "3.6"
services:
    php-fpm:
        #image: 5ii5cn/php73:latest
        build:
          context: ./ #路径
        container_name: php73
        ports:
            - "9000:9000"
            - "9501:9501"
            - "9502:9502"
            - "9503:9503"
            - "9504:9504"
        volumes:
          - ../../www:/var/www/html
          - ./conf/php.ini:/usr/local/etc/php/php.ini
        stdin_open: true
        tty: true
        privileged: true
        networks:
            cache-network:
              ipv4_address: 192.160.1.50

networks:
 cache-network:
    external:
      #name: redis-network
      name: redis5sm