version: '3.6'
services:
  elasticsearch_m10:
    image: elasticsearch:7.6.1
    container_name: elasticsearch_m10
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./master_10/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./master_10/data:/usr/share/elasticsearch/data
    ports:
      - 9210:9200
      - 9310:9300
    networks:
      es:
        ipv4_address: 192.160.1.70


  elasticsearch_s11:
    image: elasticsearch:7.6.1
    container_name: elasticsearch_s11
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./slave_11/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./slave_11/data:/usr/share/elasticsearch/data
    ports:
      - 9211:9200
      - 9311:9300
    networks:
      es:
        ipv4_address: 192.160.1.71

  elasticsearch_s12:
    image: elasticsearch:7.6.1
    container_name: elasticsearch_s12
    privileged: true
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./slave_12/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./slave_12/data:/usr/share/elasticsearch/data
    ports:
      - 9212:9200
      - 9312:9300
    networks:
      es:
        ipv4_address: 192.160.1.72

  kibana:
    image: kibana:7.6.1
    container_name: kibana
    environment:
      - "ELASTICSEARCH_HOSTS=http://192.160.1.72:9200"
      - "SERVER_PORT=5601"
      - "SERVER_HOST=0.0.0.0"
    ports:
      - 5601:5601
    networks:
      es:
        ipv4_address: 192.160.1.73

networks:
#  es:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: "192.160.1.0/16"
  es:
    #    driver: bridge
    #    ipam: #定义网段
    #      config:
    #        - subnet: "192.160.1.0/16"
    external:
      name: redis5sm