#  MySQL 配置：地址，用户名，密码
my_addr = "vmhost:3307"
my_user = "root"
my_pass = "123456"
my_charset = "utf8"

# Elasticsearch地址
es_addr = "vmhost:9210"
es_user = ""
es_pass = ""

# 存储数据的位置（如果binlog偏移不一致导致同步失败时根据当时相关偏移进行调整即可、/var/master.info）
data_dir = "/var"

# Inner Http status address
stat_addr = "vmhost:12800"
stat_path = "/es"
# pseudo server id like a slave
server_id = 1001
# mysql or mariadb
flavor = "mysql"
# mysqldump execution path
# mysqldump = "mysqldump"
# minimal items to be inserted in one bulk
bulk_size = 1024

# force flush the pending requests if we don't have enough items >= bulk_size
flush_bulk_time = "200ms"


# Ignore table without primary key
skip_no_pk_table = false

# elasticsearch 与 mysql 同步时对应的数据库名称
# mysql的数据源
[[source]]
schema = "xiu_user"

# 数据库表名精准配置方式
# tables = ["goods"]
# 数据库表名正则匹配方式
tables = ["user_base_info_[0-9]{2}"]

# es 映射的mapping
[[rule]]
schema = "xiu_user"
table = "user_base_info_[0-9]{2}"

# es的索引名
index = "user_base_info"
type = "link_info"