version: "3.6"
services:
    nginx:
        image: my_nginx
        build:
           context: ./ #路径
        container_name: nginx
        working_dir: /usr/local/nginx
        ports:
           - "80:80"
           - "443:443"
        stdin_open: true
        networks:
           cache-network:
              ipv4_address: 192.168.5.6
        tty: true
        privileged: true
        volumes:
            - ./conf:/conf
            -  ../www:/var/www/html
networks:
    cache-network:
      external:
         name: redis-network