cluster.name: elasticsearch-cluster
node.name: es-master-10
network.host: 0.0.0.0
network.publish_host: 192.160.1.70
http.port: 9200
transport.tcp.port: 9300
http.cors.enabled: true
http.cors.allow-origin: "*"
node.master: true
node.data: true
discovery.zen.ping.unicast.hosts: ["192.160.1.70:9300","192.160.1.71:9300","192.160.1.72:9300"]
discovery.zen.minimum_master_nodes: 1
cluster.initial_master_nodes: es-master-10
